
# MySQL8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ca?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis
  data:
    redis:
      host: localhost
      port: 6379

  # SQL
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
